---
#the hdd_disk_name and nvme_disk_name variables are defined in the inventory file sent by backend.
    - name: Create GPT label on HDD & NVME disk
      command: parted --script {{ item }} mklabel gpt
      loop:
        - "{{ hdd_disk_name }}"
        - "{{ nvme_disk_name }}"

    - name: Format disks with ext4 filesystem
      command: mkfs.ext4 {{ item }}
      loop:
        - "{{ hdd_disk_name }}"
        - "{{ nvme_disk_name }}"
  
    - name: Create directories for disk mounts
      file:
        path: "{{ item }}"
        state: directory
      loop:
        - /mnt/cold-disk
        - /mnt/hot-disk

    - name: Mount disks
      mount:
        path: "{{ item.0 }}"
        src: "{{ item.1 }}"
        fstype: ext4
        opts: defaults
        state: mounted
      loop:
        - ["/mnt/cold-disk", "{{ hdd_disk_name }}"]
        - ["/mnt/hot-disk", "{{ nvme_disk_name }}"]

    - name: Add entry to /etc/fstab for cold disk
      lineinfile:
        path: /etc/fstab
        line: "{{ hdd_disk_name }} /mnt/cold-disk ext4 defaults 0 2"
        create: yes
    - name: Add entry to /etc/fstab for hot disk
      lineinfile:
        path: /etc/fstab
        line: "{{ nvme_disk_name }} /mnt/hot-disk ext4 defaults 0 2"
        create: yes
    
    - name: Create systemd service file for SeaweedFS volume Server # -dataCenter=DC1  -rack=rack1 to check later on!!
      copy:
        dest: /etc/systemd/system/seaweedvolume.service
        content: |
                  [Unit]
                  Description=SeaweedFS Volume Server
                  After=network.target
                  
                  [Service]
                  ExecStart=/usr/local/bin/weed volume -max=5 -mserver={{ hostvars['master1'].ansible_host }}:9333,{{ hostvars['master2'].ansible_host }}:9333,{{ hostvars['master3'].ansible_host }}:9333 -port=8080 -disk=ssd,hdd -dir=/mnt/hot-disk,/mnt/cold-disk -dataCenter=DC1  -rack=rack1 -metricsPort=9326
                  
                  Restart=always
                  User=root
                  
                  [Install]
                  WantedBy=multi-user.target

    - name:  apply changes with daemon_reload
      systemd:
          daemon_reload: true

    - name: Ensure SeaweedFS Volume Server service is enabled and started
      systemd:
        name: seaweedvolume
        state: started
        enabled: true